packages:
  - 'packages/*'
  - 'apps/*'
  - 'tooling/*'
  - '!packages/web-ui/catalyst-ui-kit/**'
  - '!**/node_modules'
  - '!**/.turbo'
  - '!**/dist'
  - '!**/build'
  - '!**/.next'
  - '!**/coverage'
