/**
 * Functional transform to add file headers to auto-generated component files
 *
 * Adds standardized warning headers to indicate files are auto-generated and
 * should not be manually edited. Handles different file types and preserves
 * existing directives like 'use client'.
 *
 * Header format:
 * ```
 * // WARNING: This file is auto-generated and will be overwritten.
 * // Auto generated on DEVELOPMENT
 * ```
 *
 * Examples of transformations:
 *
 * Regular component file:
 * ```
 * import React from 'react'
 *
 * export function Component() {
 * // becomes:
 * // WARNING: This file is auto-generated and will be overwritten.
 * // Auto generated on DEVELOPMENT
 *
 * import React from 'react'
 *
 * export function Component() {
 * ```
 *
 * 'use client' component file:
 * ```
 * 'use client'
 *
 * import React from 'react'
 * // becomes:
 * 'use client'
 * // WARNING: This file is auto-generated and will be overwritten.
 * // Auto generated on DEVELOPMENT
 *
 * import React from 'react'
 * ```
 *
 * Uses CLI framework Result types for consistent error handling.
 * Pure functional interface with no classes.
 */

import type { Result, CLIError } from '@esteban-url/trailhead-cli/core';
import { createTransformMetadata, executeTransform, type TransformResult } from '../utils.js';

/**
 * Transform metadata
 */
export const fileHeadersTransform = createTransformMetadata(
  'file-headers',
  'Add file headers to components',
  'format'
);

/**
 * Add auto-generated warning headers to component files
 *
 * Transform process:
 * 1. Check if file already has auto-generated header (skip if present)
 * 2. Detect 'use client' directive at file start
 * 3. Generate header with timestamp (DEVELOPMENT or ISO date)
 * 4. Insert header in appropriate location preserving existing directives
 *
 * Examples:
 * - Adds `// WARNING: This file is auto-generated and will be overwritten.` to top of file
 * - Adds `// Auto generated on DEVELOPMENT` timestamp
 * - Preserves 'use client' directive placement
 */
export function transformFileHeaders(input: string): Result<TransformResult, CLIError> {
  return executeTransform(() => {
    let content = input;
    const warnings: string[] = [];
    let changed = false;

    /////////////////////////////////////////////////////////////////////////////////
    // Phase 1: Check for Existing Auto-Generated Header
    // Finds:
    //        // WARNING: This file is auto-generated and will be overwritten.
    //
    /////////////////////////////////////////////////////////////////////////////////
    const hasAutoGeneratedHeader = content.includes(
      'WARNING: This file is auto-generated and will be overwritten.'
    );

    if (hasAutoGeneratedHeader) {
      warnings.push('File already has auto-generated header');
      return { content, changed: false, warnings };
    }

    /////////////////////////////////////////////////////////////////////////////////
    // Phase 2: Detect 'use client' Directive
    // Finds:
    //        'use client'
    //
    /////////////////////////////////////////////////////////////////////////////////
    const hasUseClient = content.startsWith("'use client'");

    /////////////////////////////////////////////////////////////////////////////////
    // Phase 3: Generate Header Content
    // Creates timestamp-based header with warning message
    // Production: ISO timestamp, Development: "DEVELOPMENT"
    //
    /////////////////////////////////////////////////////////////////////////////////
    const generatedOnLiteral =
      process.env.NODE_ENV === 'production' ? new Date().toISOString() : 'DEVELOPMENT';
    const header =
      '// WARNING: This file is auto-generated and will be overwritten.\n// Auto generated on ' +
      generatedOnLiteral +
      '\n\n';

    /////////////////////////////////////////////////////////////////////////////////
    // Phase 4: Insert Header in Appropriate Location
    // Preserves 'use client' directive placement while adding header
    //
    /////////////////////////////////////////////////////////////////////////////////
    if (hasUseClient) {
      // Add header after 'use client'
      const useClientLine = "'use client'\n";
      const afterUseClient = content.substring(useClientLine.length);

      // Check if there's already a blank line after 'use client'
      const hasBlankLine = afterUseClient.startsWith('\n');

      if (hasBlankLine) {
        // Replace the blank line with header + blank line
        content = useClientLine + header + afterUseClient;
      } else {
        // Add header with blank line
        content = useClientLine + header + '\n' + afterUseClient;
      }
      changed = true;
    } else {
      // Add header at the beginning
      content = header + '\n' + content;
      changed = true;
    }

    return { content, changed, warnings };
  });
}
