/**
 * Functional transform to add file headers to auto-generated component files
 *
 * Adds standardized warning headers at the top of files to indicate they are
 * auto-generated and should not be manually edited.
 *
 * Header format:
 * ```
 * // WARNING: This file is auto-generated and will be overwritten.
 * // Auto generated on DEVELOPMENT
 * ```
 *
 * Uses CLI framework Result types for consistent error handling.
 * Pure functional interface with no classes.
 */

import type { Result, CLIError } from '@esteban-url/cli/core';
import { createTransformMetadata, executeTransform, type TransformResult } from '../utils.js';

/**
 * Transform metadata
 */
export const fileHeadersTransform = createTransformMetadata(
  'file-headers',
  'Add file headers to components',
  'format'
);

/**
 * Add auto-generated warning headers to the top of component files
 *
 * Transform process:
 * 1. Check if file already has auto-generated header (skip if present)
 * 2. Generate header with timestamp (DEVELOPMENT or ISO date)
 * 3. Add header at the very beginning of the file
 *
 * Examples:
 * - Adds `// WARNING: This file is auto-generated and will be overwritten.` at top
 * - Adds `// Auto generated on DEVELOPMENT` timestamp
 */
export function transformFileHeaders(input: string): Result<TransformResult, CLIError> {
  return executeTransform(() => {
    const content = input;
    const warnings: string[] = [];

    /////////////////////////////////////////////////////////////////////////////////
    // Phase 1: Check for Existing Header
    // Finds:
    //        'WARNING: This file is auto-generated and will be overwritten.'
    //        to avoid adding duplicate headers
    //
    /////////////////////////////////////////////////////////////////////////////////
    const hasAutoGeneratedHeader = content.includes(
      'WARNING: This file is auto-generated and will be overwritten.'
    );

    if (hasAutoGeneratedHeader) {
      warnings.push('File already has auto-generated header');
      return { content, changed: false, warnings };
    }

    /////////////////////////////////////////////////////////////////////////////////
    // Phase 2: Generate Header Content
    //
    // From:  (empty file or file without header)
    // To:    // WARNING: This file is auto-generated and will be overwritten.
    //        // Auto generated on DEVELOPMENT
    //
    /////////////////////////////////////////////////////////////////////////////////
    const generatedOnLiteral =
      process.env.NODE_ENV === 'production' ? new Date().toISOString() : 'DEVELOPMENT';
    const header =
      '// WARNING: This file is auto-generated and will be overwritten.\n// Auto generated on ' +
      generatedOnLiteral +
      '\n\n';

    /////////////////////////////////////////////////////////////////////////////////
    // Phase 3: Prepend Header to File
    //
    // From:  import React from 'react';
    // To:    // WARNING: This file is auto-generated and will be overwritten.
    //        // Auto generated on DEVELOPMENT
    //
    //        import React from 'react';
    //
    /////////////////////////////////////////////////////////////////////////////////
    const newContent = header + content;

    return { content: newContent, changed: true, warnings };
  });
}
