name: 🚀 Enhancement Request
description: Suggest an enhancement or improvement to existing functionality
title: "[Enhancement]: "
labels: ["enhancement", "needs-triage"]
projects: ["esteban-url/trailhead"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an enhancement! Please fill out the information below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this enhancement solve? What pain point are you experiencing?
      placeholder: Describe the current limitation or inefficiency you're facing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented? How should this enhancement work?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider? What workarounds are you currently using?
      placeholder: Describe any alternative solutions or workarounds...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, code examples, or relevant information about the enhancement request.
      placeholder: Any additional details that might be helpful...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this enhancement to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current work
        - Critical - Major pain point
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project does this enhancement relate to?
      options:
        - CLI Framework (@esteban-url/trailhead-cli)
        - Web UI Components (@esteban-url/trailhead-web-ui)
        - Documentation
        - Build System / Tooling
        - Testing Infrastructure
        - CI/CD
        - Other
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true