name: Feature Request
description: Suggest an idea for Trailhead UI
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - esteban-url
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered.

  - type: dropdown
    id: area
    attributes:
      label: Which area does this feature affect?
      multiple: true
      options:
        - Components
        - Theme System
        - CLI
        - Transform System
        - Performance
        - Developer Experience
        - Documentation
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this feature
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, mockups, or examples about the feature request here.