name: 'Setup Node.js and pnpm'
description: 'Composite action to setup Node.js and pnpm with caching'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20.11.0'
  pnpm-version:
    description: 'pnpm version to use (will use packageManager field from package.json if not specified)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache (GitHub Actions)
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-${{ runner.os }}-

    - name: Cache node_modules (GitHub Actions)
      id: cache-modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          packages/*/node_modules
          apps/*/node_modules
          tooling/*/node_modules
          ~/.cache/pnpm
        key: modules-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml', '**/package.json') }}
        restore-keys: |
          modules-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-
          modules-${{ runner.os }}-

    - name: Install dependencies
      if: steps.cache-modules.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Verify installation
      if: steps.cache-modules.outputs.cache-hit == 'true'
      shell: bash
      run: pnpm install --frozen-lockfile --offline
