/**
 * Component mapping configurations for Catalyst integration
 */

import { type ComponentMapping } from '../../core/types';

export const CATALYST_COMPONENT_MAPPINGS: ComponentMapping[] = [
  { originalName: 'Avatar', prefixedName: 'CatalystAvatar' },
  { originalName: 'AvatarButton', prefixedName: 'CatalystAvatarButton' },
  { originalName: 'Badge', prefixedName: 'CatalystBadge' },
  { originalName: 'BadgeButton', prefixedName: 'CatalystBadgeButton' },
  { originalName: 'Button', prefixedName: 'CatalystButton' },
  { originalName: 'Checkbox', prefixedName: 'CatalystCheckbox' },
  { originalName: 'CheckboxField', prefixedName: 'CatalystCheckboxField' },
  { originalName: 'CheckboxGroup', prefixedName: 'CatalystCheckboxGroup' },
  { originalName: 'Combobox', prefixedName: 'CatalystCombobox' },
  { originalName: 'ComboboxButton', prefixedName: 'CatalystComboboxButton' },
  { originalName: 'ComboboxInput', prefixedName: 'CatalystComboboxInput' },
  { originalName: 'ComboboxOption', prefixedName: 'CatalystComboboxOption' },
  { originalName: 'ComboboxOptions', prefixedName: 'CatalystComboboxOptions' },
  { originalName: 'DescriptionList', prefixedName: 'CatalystDescriptionList' },
  { originalName: 'DescriptionListItem', prefixedName: 'CatalystDescriptionListItem' },
  { originalName: 'DescriptionTerm', prefixedName: 'CatalystDescriptionTerm' },
  { originalName: 'DescriptionDetails', prefixedName: 'CatalystDescriptionDetails' },
  { originalName: 'Dialog', prefixedName: 'CatalystDialog' },
  { originalName: 'DialogTitle', prefixedName: 'CatalystDialogTitle' },
  { originalName: 'DialogDescription', prefixedName: 'CatalystDialogDescription' },
  { originalName: 'DialogBody', prefixedName: 'CatalystDialogBody' },
  { originalName: 'DialogActions', prefixedName: 'CatalystDialogActions' },
  { originalName: 'Divider', prefixedName: 'CatalystDivider' },
  { originalName: 'Dropdown', prefixedName: 'CatalystDropdown' },
  { originalName: 'DropdownButton', prefixedName: 'CatalystDropdownButton' },
  { originalName: 'DropdownDivider', prefixedName: 'CatalystDropdownDivider' },
  { originalName: 'DropdownHeader', prefixedName: 'CatalystDropdownHeader' },
  { originalName: 'DropdownItem', prefixedName: 'CatalystDropdownItem' },
  { originalName: 'DropdownLabel', prefixedName: 'CatalystDropdownLabel' },
  { originalName: 'DropdownMenu', prefixedName: 'CatalystDropdownMenu' },
  { originalName: 'DropdownSection', prefixedName: 'CatalystDropdownSection' },
  { originalName: 'DropdownShortcut', prefixedName: 'CatalystDropdownShortcut' },
  { originalName: 'DropdownDescription', prefixedName: 'CatalystDropdownDescription' },
  { originalName: 'DropdownHeading', prefixedName: 'CatalystDropdownHeading' },
  { originalName: 'Fieldset', prefixedName: 'CatalystFieldset' },
  { originalName: 'FieldGroup', prefixedName: 'CatalystFieldGroup' },
  { originalName: 'Field', prefixedName: 'CatalystField' },
  { originalName: 'Label', prefixedName: 'CatalystLabel' },
  { originalName: 'Description', prefixedName: 'CatalystDescription' },
  { originalName: 'ErrorMessage', prefixedName: 'CatalystErrorMessage' },
  { originalName: 'Heading', prefixedName: 'CatalystHeading' },
  { originalName: 'Subheading', prefixedName: 'CatalystSubheading' },
  { originalName: 'Input', prefixedName: 'CatalystInput' },
  { originalName: 'InputGroup', prefixedName: 'CatalystInputGroup' },
  { originalName: 'Link', prefixedName: 'CatalystLink' },
  { originalName: 'Strong', prefixedName: 'CatalystStrong' },
  { originalName: 'Code', prefixedName: 'CatalystCode' },
  { originalName: 'Listbox', prefixedName: 'CatalystListbox' },
  { originalName: 'ListboxButton', prefixedName: 'CatalystListboxButton' },
  { originalName: 'ListboxLabel', prefixedName: 'CatalystListboxLabel' },
  { originalName: 'ListboxOption', prefixedName: 'CatalystListboxOption' },
  { originalName: 'ListboxOptions', prefixedName: 'CatalystListboxOptions' },
  { originalName: 'ListboxSelectedOption', prefixedName: 'CatalystListboxSelectedOption' },
  { originalName: 'Navbar', prefixedName: 'CatalystNavbar' },
  { originalName: 'NavbarDivider', prefixedName: 'CatalystNavbarDivider' },
  { originalName: 'NavbarItem', prefixedName: 'CatalystNavbarItem' },
  { originalName: 'NavbarLabel', prefixedName: 'CatalystNavbarLabel' },
  { originalName: 'NavbarSection', prefixedName: 'CatalystNavbarSection' },
  { originalName: 'NavbarSpacer', prefixedName: 'CatalystNavbarSpacer' },
  { originalName: 'Pagination', prefixedName: 'CatalystPagination' },
  { originalName: 'PaginationGap', prefixedName: 'CatalystPaginationGap' },
  { originalName: 'PaginationList', prefixedName: 'CatalystPaginationList' },
  { originalName: 'PaginationNext', prefixedName: 'CatalystPaginationNext' },
  { originalName: 'PaginationPage', prefixedName: 'CatalystPaginationPage' },
  { originalName: 'PaginationPrevious', prefixedName: 'CatalystPaginationPrevious' },
  { originalName: 'Radio', prefixedName: 'CatalystRadio' },
  { originalName: 'RadioField', prefixedName: 'CatalystRadioField' },
  { originalName: 'RadioGroup', prefixedName: 'CatalystRadioGroup' },
  { originalName: 'Select', prefixedName: 'CatalystSelect' },
  { originalName: 'Sidebar', prefixedName: 'CatalystSidebar' },
  { originalName: 'SidebarBody', prefixedName: 'CatalystSidebarBody' },
  { originalName: 'SidebarDivider', prefixedName: 'CatalystSidebarDivider' },
  { originalName: 'SidebarFooter', prefixedName: 'CatalystSidebarFooter' },
  { originalName: 'SidebarHeader', prefixedName: 'CatalystSidebarHeader' },
  { originalName: 'SidebarHeading', prefixedName: 'CatalystSidebarHeading' },
  { originalName: 'SidebarItem', prefixedName: 'CatalystSidebarItem' },
  { originalName: 'SidebarLabel', prefixedName: 'CatalystSidebarLabel' },
  { originalName: 'SidebarSection', prefixedName: 'CatalystSidebarSection' },
  { originalName: 'SidebarSpacer', prefixedName: 'CatalystSidebarSpacer' },
  { originalName: 'SidebarLayout', prefixedName: 'CatalystSidebarLayout' },
  { originalName: 'StackedLayout', prefixedName: 'CatalystStackedLayout' },
  { originalName: 'Switch', prefixedName: 'CatalystSwitch' },
  { originalName: 'SwitchField', prefixedName: 'CatalystSwitchField' },
  { originalName: 'SwitchGroup', prefixedName: 'CatalystSwitchGroup' },
  { originalName: 'Table', prefixedName: 'CatalystTable' },
  { originalName: 'TableBody', prefixedName: 'CatalystTableBody' },
  { originalName: 'TableCell', prefixedName: 'CatalystTableCell' },
  { originalName: 'TableHead', prefixedName: 'CatalystTableHead' },
  { originalName: 'TableHeader', prefixedName: 'CatalystTableHeader' },
  { originalName: 'TableRow', prefixedName: 'CatalystTableRow' },
  { originalName: 'Text', prefixedName: 'CatalystText' },
  { originalName: 'TextLink', prefixedName: 'CatalystTextLink' },
  { originalName: 'Textarea', prefixedName: 'CatalystTextarea' },
  { originalName: 'TouchTarget', prefixedName: 'CatalystTouchTarget' },
  { originalName: 'Alert', prefixedName: 'CatalystAlert' },
  { originalName: 'AlertActions', prefixedName: 'CatalystAlertActions' },
  { originalName: 'AlertBody', prefixedName: 'CatalystAlertBody' },
  { originalName: 'AlertDescription', prefixedName: 'CatalystAlertDescription' },
  { originalName: 'AlertTitle', prefixedName: 'CatalystAlertTitle' },
  { originalName: 'AuthLayout', prefixedName: 'CatalystAuthLayout' },
];

export const CATALYST_PREFIX = 'Catalyst';

export function getCatalystMapping(originalName: string): ComponentMapping | undefined {
  return CATALYST_COMPONENT_MAPPINGS.find(mapping => mapping.originalName === originalName);
}

export function getAllOriginalNames(): string[] {
  return CATALYST_COMPONENT_MAPPINGS.map(mapping => mapping.originalName);
}

export function getAllPrefixedNames(): string[] {
  return CATALYST_COMPONENT_MAPPINGS.map(mapping => mapping.prefixedName);
}
